name: Reorganizar arquivos index e sobre

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Reorganizar index v3 e sobre v2
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git mv "index.html" "index-v2.html"
          git mv "index v3.html" "index.html"
          git mv "sobre.html" "sobre-v1.html"
          git mv "sobre v2.html" "sobre.html"
          git commit -m "Coloca index v3 e sobre v2 no ar"
          git push
