name: Atualizar index para v11

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Coloca cuca-landing-v11 no ar
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git mv "index.html" "index-v3.html"
          git mv "cuca-landing-v11.html" "index.html"
          git commit -m "Coloca cuca-landing-v11 no ar"
          git push
